"""
Phase 1: Bootstrap S3 Remote State Bucket (pre-infra/bootstrap).
"""

from pathlib import Path
from tools.utils.ui import log_phase, log_info, log_success
from tools.utils.process import run_cmd

def run_phase_1(repo_root: Path, config: dict, outputs: dict):
    """Executes Phase 1: Provisions S3 Remote State bucket with dynamic project name."""
    log_phase(1, 11, "Bootstrap S3 Remote State Bucket (pre-infra/bootstrap)")
    target_dir = repo_root / "aws/pre-infra/bootstrap"
    
    project_name = config.get("github_repo_name") or "cleanmybelly"
    aws_region = config.get("aws_region") or "us-east-1"

    # Dynamically generate local terraform.tfvars for the bootstrap module
    tfvars_file = target_dir / "terraform.tfvars"
    tfvars_content = (
        f"# Auto-generated by cleanmybelly Bootstrap CLI tool\n"
        f'aws_region      = "{aws_region}"\n'
        f'project_name    = "{project_name}"\n'
        f'project_version = "v1"\n'
    )
    tfvars_file.write_text(tfvars_content, encoding="utf-8")
    log_info(f"Generated dynamic tfvars for project '{project_name}' in region '{aws_region}'...")

    log_info("Initializing Terraform in aws/pre-infra/bootstrap...")
    run_cmd(["terraform", "init"], cwd=target_dir)

    log_info("Applying Terraform configuration...")
    tf_vars = [
        f"-var=project_name={project_name}",
        f"-var=aws_region={aws_region}"
    ]
    run_cmd(["terraform", "apply", "-auto-approve"] + tf_vars, cwd=target_dir)

    res = run_cmd(["terraform", "output", "-raw", "terraform_state_bucket_name"], cwd=target_dir)
    bucket_name = res.stdout.strip()
    outputs["terraform_state_bucket"] = bucket_name
    log_success(f"S3 Remote State Bucket Created: {bucket_name}")

